package org.apache.cxf.rs.security.httpsignature;

public enum SignatureExceptionType {
    MISSING_SIGNATURE_HEADER,
    INVALID_SIGNATURE_HEADER,
    FAILED_TO_VERIFY_SIGNATURE,
    INVALID_DATA_TO_VERIFY_SIGNATURE,
    DIGEST_FAILURE,
    MISSING_DIGEST,
    DIFFERENT_DIGESTS,
    MULTIPLE_SIGNATURE_HEADERS,
    DIFFERENT_ALGORITHMS
}