/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
*/
typedef sequence<string, 1> p2Array;
typedef string p3Array[5];
typedef sequence<string> p4Array;
typedef sequence<string, 15> p5Array;
typedef sequence<string> p6Array;
typedef sequence<string, 10> p7Array;
struct ArrayType {
    string p1;
    p2Array p2;
    p3Array p3;
    p4Array p4;
    p5Array p5;
    p6Array p6;
    p7Array p7;
};
interface X {
    string
    op_a(
        in ::ArrayType part1
    );
};
