/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
*/
#include <omg/TimeBase.idl>

interface BasePortType {
    union _omg_SimpleUnion switch(long) {
        case 0:
            TimeBase::UtcT varUTCTime;
        case 1:
            long varInt;
        case 2:
            float varFloat;
    };
    union SimpleUnion switch(long) {
        case 0:
            TimeBase::UtcT varUTCTime;
        case 1:
            long varInt;
        case 2:
            float varFloat;
    };
    struct SimpleStruct {
        TimeBase::UtcT varUTCTime;
        long varInt;
        unsigned long long varTime;
    };
    TimeBase::UtcT
    echoDateTime(
        in TimeBase::UtcT inputDateTime
    );
    string
    echoDate(
        in string inputDate
    );
    string
    echoTime(
        in string inputTime
    );
    string
    echoGYearMonth(
        in string inputGYearMonth
    );
    string
    echoGYear(
        in string inputGYear
    );
    string
    echoGMonthDay(
        in string inputGMonthDay
    );
    string
    echoGMonth(
        in string inputGMonth
    );
    string
    echoGDay(
        in string inputGDay
    );
    void
    set_interval(
        in ::TimeBase::IntervalT interval
    );
};
