<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->

<definitions name="c/epr.idl" 
             targetNamespace="http://schemas.apache.org/idl/c/epr.idl" 
             xmlns:tns="http://schemas.apache.org/idl/c/epr.idl" 
             xmlns:corbatm="http://schemas.apache.org/typemap/corba/c/epr.idl" 
             xmlns:corba="http://cxf.apache.org/bindings/corba" 
             xmlns:ns1="http://schemas.apache.org/idl/c/epr.idl/corba/typemap/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:xs="http://www.w3.org/2001/XMLSchema" 
             xmlns:addressing="http://www.w3.org/2005/08/addressing" 
             xmlns:xsd1="http://schemas.apache.org/idltypes/c/epr.idl" 
             xmlns="http://schemas.xmlsoap.org/wsdl/">
  <corba:typeMapping targetNamespace="http://schemas.apache.org/idl/c/epr.idl/corba/typemap/">
    <corba:object xmlns:addressing="http://www.w3.org/2005/08/addressing" repositoryID="IDL:omg.org/CORBA/Object/1.0" type="addressing:EndpointReferenceType" name="CORBA.Object" />
  </corba:typeMapping>
  <types>
    <schema targetNamespace="http://schemas.apache.org/idltypes/c/epr.idl" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
     <import namespace="http://www.w3.org/2005/08/addressing" 
             schemaLocation="/schemas/wsdl/ws-addr.xsd"/>
    </schema>
  </types>
  <message name="TestServer.registerResponse">
  </message>
  <message name="TestServer.register">
    <part name="cb" element="addressing:EndpointReference"/>
  </message>
  <portType name="TestServer">
    <operation name="register">
      <input name="register" message="tns:TestServer.register"/>
      <output name="registerResponse" message="tns:TestServer.registerResponse"/>
    </operation>
  </portType>
  <binding name="TestServerCORBABinding" type="tns:TestServer">
    <corba:binding repositoryID="IDL:TestServer:1.0" />
    <operation name="register">
      <corba:operation name="register">
        <corba:param xmlns:ns1="http://schemas.apache.org/idl/c/epr.idl/corba/typemap/" mode="in" name="cb" idltype="ns1:CORBA.Object" />
      </corba:operation>
      <input name="register">
      </input>
      <output name="registerResponse">
      </output>
    </operation>
  </binding>
</definitions>
