/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.cxf.jaxws.implicitheader;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * Document/literal wrapped SEI (as generated by wsdl2java -exsh true) where the "auth" parameter
 * maps to an implicit soap:header, i.e. one that is only declared on the WSDL binding.
 */
@WebService(name = "EchoPortType", targetNamespace = "urn:cxf:implicitheader")
public interface EchoPortType {

    @WebMethod(operationName = "echo")
    @RequestWrapper(localName = "echo", targetNamespace = "urn:cxf:implicitheader")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "urn:cxf:implicitheader")
    @WebResult(name = "return", targetNamespace = "urn:cxf:implicitheader")
    String echo(@WebParam(name = "in", targetNamespace = "urn:cxf:implicitheader") String in,
                @WebParam(name = "auth", targetNamespace = "urn:cxf:implicitheader", partName = "auth",
                          header = true)
                String auth);
}
