github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "[0-9]+.[0-9]+.x-fixes"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
