<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="StockService" targetNamespace="http://rpc.classnoanno.fortest.tools.cxf.apache.org/" xmlns:tns="http://rpc.classnoanno.fortest.tools.cxf.apache.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="getPrice">
    <wsdl:part name="arg0" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getPriceResponse">
    <wsdl:part name="return" type="xsd:float">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Stock">
    <wsdl:operation name="getPrice">
      <wsdl:input name="getPrice" message="tns:getPrice">
    </wsdl:input>
      <wsdl:output name="getPriceResponse" message="tns:getPriceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="StockServiceSoapBinding" type="tns:Stock">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getPrice">
      <soap:operation soapAction="" style="rpc"/>
      <wsdl:input name="getPrice">
        <soap:body use="literal" namespace="http://rpc.classnoanno.fortest.tools.cxf.apache.org/"/>
      </wsdl:input>
      <wsdl:output name="getPriceResponse">
        <soap:body use="literal" namespace="http://rpc.classnoanno.fortest.tools.cxf.apache.org/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StockService">
    <wsdl:port name="StockPort" binding="tns:StockServiceSoapBinding">
      <soap:address location="http://localhost"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>