#define _a

#ifdef _a
#define _b
#else
 #define _c
#endif

module c
{
  interface C {
  #ifdef _b 
    const boolean b = TRUE;
  #else
    const boolean b = FALSE;
  #endif /* #endif _b */

#ifndef _c
    const boolean c = FALSE;
#else
    const boolean c = TRUE;
#endif  // endif _c

#if 0
    const char d = 'd';
#endif 
#if 1
    const char e = 'e';
#endif
#if true
    const char f = 'f';
#endif
  };
};

