/* 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
*/


typedef long LongArray[10];
typedef long LongArrayArray[10][100];
typedef long LongArrayArrayArray[10][100][1000];
typedef long LongArrayArrayArrayArray[10][100][1000][10000];

typedef short ShortArray[2];
typedef short ShortArrayArray[2][4];
typedef short ShortArrayArrayArrayArray[2][4][8];
typedef short ShortArrayArrayArrayArrayArray[2][4][8][16];


typedef long myLong;

typedef myLong MyLongArray[10];
typedef myLong MyLongArrayArray[10][100];
typedef myLong MyLongArrayArrayArray[10][100][1000];
typedef myLong MyLongArrayArrayArrayArray[10][100][1000][10000];


typedef string<35> BuildingAddress_T;
typedef BuildingAddress_T BuildingAddress_6_T[6];
    