<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
-->
<wsdl:definitions targetNamespace="http://cxf.apache.org/bindings/corba/idl/HelloWorld" xmlns:tns="http://cxf.apache.org/bindings/corba/idl/HelloWorld" xmlns:corba="http://cxf.apache.org/bindings/corba" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <corba:typeMapping targetNamespace="http://cxf.apache.org/bindings/corba/idl/HelloWorld/typemap" />
  <wsdl:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://cxf.apache.org/bindings/corba/idl/HelloWorld" xmlns="http://cxf.apache.org/bindings/corba/idl/HelloWorld" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="greetMe">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return_message" type="xs:string">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="greetMeResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="greetMeResponse">
    <wsdl:part name="outparameter" element="tns:greetMeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="greetMe">
    <wsdl:part name="inparameter" element="tns:greetMe">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloWorld">
    <wsdl:operation name="greetMe">
      <wsdl:input name="greetMeRequest" message="tns:greetMe">
    </wsdl:input>
      <wsdl:output name="greetMeResponse" message="tns:greetMeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloWorldCORBABinding" type="tns:HelloWorld">
    <corba:binding repositoryID="IDL:HelloWorld:1.0" />
    <wsdl:operation name="greetMe">
      <corba:operation name="greetMe">
        <corba:param mode="in" idltype="corba:string" name="return_message" />
        <corba:return idltype="corba:string" name="return" />
      </corba:operation>
      <wsdl:input name="greetMeRequest">
      </wsdl:input>
      <wsdl:output name="greetMeResponse">
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloWorldCORBAService">
    <wsdl:port name="HelloWorldCORBAPort" binding="tns:HelloWorldCORBABinding">
      <corba:address location="IOR:" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
