<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/contract/DoubleIt" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsaws="http://www.w3.org/2005/08/addressing" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802" name="DoubleIt" targetNamespace="http://www.example.org/contract/DoubleIt">
    <wsdl:import location="src/test/resources/DoubleItLogical.wsdl" namespace="http://www.example.org/contract/DoubleIt"/>
    <wsdl:binding name="DoubleItNoSecurityBinding" type="tns:DoubleItPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction=""/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="DoubleItService">
        <wsdl:port name="DoubleIt3DESEncryptionPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleIt3DESEncryption"/>
        </wsdl:port>
        <wsdl:port name="DoubleItUsernameTokenPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItUsernameToken"/>
        </wsdl:port>
        <wsdl:port name="DoubleItUsernameTokenPort2" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItUsernameToken2"/>
        </wsdl:port>
        <wsdl:port name="DoubleItUsernameTokenPort3" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItUsernameToken3"/>
        </wsdl:port>
        <wsdl:port name="DoubleItUsernameTokenNoValPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItUsernameTokenNoVal"/>
        </wsdl:port>
        <wsdl:port name="DoubleItEncryptedPasswordPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItEncryptedPassword"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignedTimestampPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignedTimestamp"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignaturePort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignature"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignaturePort2" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignature2"/>
        </wsdl:port>
        <wsdl:port name="DoubleItAsymmetricPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItAsymmetric"/>
        </wsdl:port>
        <wsdl:port name="DoubleItAsymmetricEncryptBeforeSigningPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItAsymmetricEncryptBeforeSigning"/>
        </wsdl:port>
        <wsdl:port name="DoubleItEncryptionPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItEncryption"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureNegativeClientPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureNegativeClient"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureNegativeClientPort2" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureNegativeClient2"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureNegativeServerPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureNegativeServer"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureNegativeServerPort2" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureNegativeServer2"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignedSAMLPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignedSAML"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureConfigPort" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureConfig"/>
        </wsdl:port>
        <wsdl:port name="DoubleItSignatureConfigPort2" binding="tns:DoubleItNoSecurityBinding">
            <soap:address location="http://localhost:9001/DoubleItSignatureConfig2"/>
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>
