<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:tns="http://apache.cxf.org/" 
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
	xmlns:wssec11test="http://WSSec/wssec11"
	xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsa10="http://www.w3.org/2005/08/addressing" 
	xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"
	targetNamespace="http://apache.cxf.org/">
	

	<wsp:Policy wsu:Id="UX_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UX_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UX_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UX-NoTimestamp_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UX-NoTimestamp_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UX-NoTimestamp_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UXD_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UXD_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UXD_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UX-SEES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptSignature />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UX-SEES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UX-SEES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UXD-SEES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptSignature />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UXD-SEES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UXD-SEES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="A_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A-NoTimestamp_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A-NoTimestamp_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="A-NoTimestamp_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="AD_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="AD_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="AD_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A-ES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptBeforeSigning />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="A-ES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="A-ES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="AD-ES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptBeforeSigning />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="AD-ES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="AD-ES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-NoTimestamp_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-NoTimestamp_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X-NoTimestamp_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-AES128_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-AES128_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X-AES128_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-AES192_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic192 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-AES192_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X-AES192_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>


	<wsp:Policy wsu:Id="X-TripleDES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:TripleDes />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="X-TripleDES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="X-TripleDES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="XD_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireDerivedKeys />
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="XD_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="XD_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>


	<wsp:Policy wsu:Id="XD-ES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptBeforeSigning />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireDerivedKeys />
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="XD-ES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="XD-ES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

	<wsp:Policy wsu:Id="XD-SEES_IPingService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SymmetricBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:ProtectionToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
									<wsp:Policy>
										<sp:RequireDerivedKeys />
										<sp:RequireThumbprintReference />
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:ProtectionToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:EncryptSignature />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:SymmetricBinding>
				<sp:EndorsingSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:RequireDerivedKeys />
								<sp:RequireThumbprintReference />
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:EndorsingSupportingTokens>
				<sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
						<sp:RequireSignatureConfirmation />
					</wsp:Policy>
				</sp:Wss11>
				<sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportIssuedTokens />
						<sp:RequireClientEntropy />
						<sp:RequireServerEntropy />
					</wsp:Policy>
				</sp:Trust10>
				<wsap:UsingAddressing />
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="XD-SEES_IPingService_echo_Input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="XD-SEES_IPingService_echo_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
					<sp:Header Name="To"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="From"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="FaultTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="ReplyTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="MessageID"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="RelatesTo"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
					<sp:Header Name="Action"
						Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
				</sp:SignedParts>
				<sp:EncryptedParts
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<sp:Body />
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>


	<wsdl:import location="WsSecurity11.wsdl" namespace="http://WSSec/wssec11" />
	<wsdl:types />
	<wsdl:binding name="K_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#K_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#K_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#K_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="K-NoTimestamp_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#K-NoTimestamp_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#K-NoTimestamp_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference
					URI="#K-NoTimestamp_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="KD_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#KD_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#KD_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#KD_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="KD-ES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#KD-ES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#KD-ES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#KD-ES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="UX_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#UX_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#UX_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#UX_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="UX-NoTimestamp_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#UX-NoTimestamp_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference
					URI="#UX-NoTimestamp_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference
					URI="#UX-NoTimestamp_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="UXD_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#UXD_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#UXD_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#UXD_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="UX-SEES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#UX-SEES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#UX-SEES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#UX-SEES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="UXD-SEES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#UXD-SEES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#UXD-SEES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#UXD-SEES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="A_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#A_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#A_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#A_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="A-NoTimestamp_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#A-NoTimestamp_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#A-NoTimestamp_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference
					URI="#A-NoTimestamp_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="AD_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#AD_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#AD_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#AD_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="A-ES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#A-ES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#A-ES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#A-ES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="AD-ES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#AD-ES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#AD-ES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#AD-ES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="X_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#X_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#X_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#X_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="X-NoTimestamp_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#X-NoTimestamp_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#X-NoTimestamp_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference
					URI="#X-NoTimestamp_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="X-AES128_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#X-AES128_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#X-AES128_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#X-AES128_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="X-AES192_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#X-AES192_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#X-AES192_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#X-AES192_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="X-TripleDES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#X-TripleDES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#X-TripleDES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#X-TripleDES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="XD_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#XD_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#XD_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#XD_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="XD-ES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#XD-ES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#XD-ES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#XD-ES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
	<wsdl:binding name="XD-SEES_IPingService" type="wssec11test:IPingService">
		<wsp:PolicyReference URI="#XD-SEES_IPingService_policy" />
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />

		<wsdl:operation name="echo">
			<soap12:operation soapAction="http://WSSec/wssec11/echo"
				style="document" />
			<wsdl:input>
				<wsp:PolicyReference URI="#XD-SEES_IPingService_echo_Input_policy" />
				<soap12:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<wsp:PolicyReference URI="#XD-SEES_IPingService_echo_output_policy" />
				<soap12:body use="literal" />
			</wsdl:output>
		</wsdl:operation>

	</wsdl:binding>
</wsdl:definitions>
