<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- a partial wsdl to test jsr 224 5.2.5.5 -->
<!--
                * Licensed to the Apache Software Foundation (ASF) under one * or more
                contributor license agreements. See the NOTICE file * distributed with
                this work for additional information * regarding copyright ownership.
                The ASF licenses this file * to you under the Apache License, Version
                2.0 (the * "License"); you may not use this file except in compliance
                * with the License. You may obtain a copy of the License at * *
                http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by
                applicable law or agreed to in writing, * software distributed under
                the License is distributed on an * "AS IS" BASIS, WITHOUT WARRANTIES
                OR CONDITIONS OF ANY * KIND, either express or implied. See the
                License for the * specific language governing permissions and
                limitations * under the License.
        -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://jaxws.systest.cxf.apache.org/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://jaxws.systest.cxf.apache.org/" name="AddNumbersImplPartial1Service">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://jaxws.systest.cxf.apache.org/" schemaLocation="AddNumbersImplPartial1Service_schema1.xsd"/>
        </xsd:schema>
    </types>
    <message name="addTwoNumbers">
        <part name="parameters" element="tns:addTwoNumbers"/>
    </message>
    <message name="addTwoNumbersResponse">
        <part name="parameters" element="tns:addTwoNumbersResponse"/>
    </message>
    <portType name="AddNumbersImplPartial1">
        <operation name="addTwoNumbers">
            <input message="tns:addTwoNumbers"/>
            <output message="tns:addTwoNumbersResponse"/>
        </operation>
    </portType>
    <!-- end here -->
</definitions>
