<?xml version="1.0" encoding="utf-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements. See the NOTICE file
distributed with this work for additional information
regarding copyright ownership. The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.
-->
<definitions
        xmlns:s="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://cxf.apache.org/soapfault"
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsaw="http://www.w3.org/2006/02/addressing/wsdl"
        targetNamespace="http://cxf.apache.org/soapfault"
    xmlns="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <s:schema>
            <s:import namespace="http://schemas.xmlsoap.org/soap/envelope/"
                      schemaLocation="http://schemas.xmlsoap.org/soap/envelope/"/>
        </s:schema>
    </types>
    <message name="SoapFault">
         <part name="fault" element="soapenv:Fault" />
    </message>

 

    <portType name="SoapFaultPortType">
        <operation name="SoapFault">
            <input name="SoapFault" message="tns:SoapFault" />
        </operation>
    </portType>

 

    <binding name="SoapFault_SOAPBinding" type="tns:SoapFaultPortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="SoapFault">
        <input message="tns:Soapfault">
          <soap:body use="literal"/>
        </input>
      </operation>
    </binding>

    <service name="SoapFaultService">
      <port binding="tns:SoapFault_SOAPBinding" name="SoapFaultPortType">
    <wsaw:UsingAddressing required="true"/>
    <soap:address location="http://localhost:9099/SoapFault"/>
      </port>
    </service> 
</definitions>
