<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements. See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership. The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License. You may obtain a copy of the License at
    
    http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<wsdl:definitions name="HelloWorld"
    targetNamespace="http://apache.org/stringarray"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://apache.org/stringarray"
    xmlns:x1="http://apache.org/stringarray/types"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
        <schema targetNamespace="http://apache.org/stringarray/types"
            xmlns="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
            <simpleType name="StringListType">
                <list itemType="string" />
            </simpleType>
        </schema>
    </wsdl:types>

    <wsdl:message name="StringListRequest">
        <wsdl:part type="x1:StringListType" name="in"/>
    </wsdl:message>

    <wsdl:message name="IntegerRangeResponse">
        <wsdl:part type="x1:StringListType" name="out"/>
    </wsdl:message>

    <wsdl:portType name="StringListTest">
        <wsdl:operation name="StringListTest">
            <wsdl:input message="tns:StringListRequest"
                name="stringListRequest" />
            <wsdl:output message="tns:IntegerRangeResponse"
                name="integerRangeResponse" />
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="Test_SOAPBinding_RPCLit"
        type="tns:StringListTest">

        <soap:binding style="rpc"
            transport="http://schemas.xmlsoap.org/soap/http" />

        <wsdl:operation name="StringListTest">
            <soap:operation soapAction="" style="rpc" />
            <wsdl:input>
                <soap:body namespace="http://apache.org/stringarray"
                    use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="http://apache.org/stringarray"
                    use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="SOAPServiceRPCLit">
        <wsdl:port binding="tns:Test_SOAPBinding_RPCLit"
            name="SoapPortRPCLit">
            <soap:address
                location="http://localhost:9992/SOAPServiceRPCLit/SoapPort" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
