<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<wsdl:definitions name="DoubleIt"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/contract/DoubleIt"
    targetNamespace="http://www.example.org/contract/DoubleIt" 
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsaws="http://www.w3.org/2005/08/addressing" 
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
    xmlns:sp13="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200802">

    <wsdl:import location="src/test/resources/DoubleItLogical.wsdl" 
                 namespace="http://www.example.org/contract/DoubleIt"/>
                     
    <wsdl:binding name="DoubleItKerberosTransportBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosTransportPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricSupportingBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricSupportingPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosAsymmetricBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosAsymmetricPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosTransportEndorsingBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosTransportEndorsingPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosAsymmetricEndorsingBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosAsymmetricEndorsingPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricProtectionBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricProtectionPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricDerivedProtectionBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricDerivedProtectionPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosAsymmetricSignedEndorsingBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosAsymmetricSignedEndorsingPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosAsymmetricSignedEncryptedBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosAsymmetricSignedEncryptedPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricEndorsingEncryptedBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricEndorsingEncryptedPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:binding name="DoubleItKerberosSymmetricSignedEndorsingEncryptedBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItKerberosSymmetricSignedEndorsingEncryptedPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="DoubleItService">
        <wsdl:port name="DoubleItKerberosTransportPort" binding="tns:DoubleItKerberosTransportBinding">
            <soap:address location="https://localhost:9009/DoubleItKerberosTransport" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricPort" 
                   binding="tns:DoubleItKerberosSymmetricBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetric" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricSupportingPort" 
                   binding="tns:DoubleItKerberosSymmetricSupportingBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetricSupporting" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosAsymmetricPort"
                   binding="tns:DoubleItKerberosAsymmetricBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosAsymmetric" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosTransportEndorsingPort" 
                   binding="tns:DoubleItKerberosTransportEndorsingBinding">
            <soap:address location="https://localhost:9009/DoubleItKerberosTransportEndorsing" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosAsymmetricEndorsingPort"
                   binding="tns:DoubleItKerberosAsymmetricEndorsingBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosAsymmetricEndorsing" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricProtectionPort" 
                   binding="tns:DoubleItKerberosSymmetricProtectionBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetricProtection" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricDerivedProtectionPort" 
                   binding="tns:DoubleItKerberosSymmetricDerivedProtectionBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetricDerivedProtection" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosAsymmetricSignedEndorsingPort"
                   binding="tns:DoubleItKerberosAsymmetricSignedEndorsingBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosAsymmetricSignedEndorsing" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosAsymmetricSignedEncryptedPort"
                   binding="tns:DoubleItKerberosAsymmetricSignedEncryptedBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosAsymmetricSignedEncrypted" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricEndorsingEncryptedPort"
                   binding="tns:DoubleItKerberosSymmetricEndorsingEncryptedBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetricEndorsingEncrypted" />
        </wsdl:port>
        <wsdl:port name="DoubleItKerberosSymmetricSignedEndorsingEncryptedPort"
                   binding="tns:DoubleItKerberosSymmetricSignedEndorsingEncryptedBinding">
            <soap:address location="http://localhost:9001/DoubleItKerberosSymmetricSignedEndorsingEncrypted" />
        </wsdl:port>
    </wsdl:service>

    <wsp:Policy wsu:Id="DoubleItKerberosTransportPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:KerberosToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                            <wsp:Policy>
                                <sp:WssGssKerberosV5ApReqToken11/>
                            </wsp:Policy>
                        </sp:KerberosToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedSupportingTokens>
                <wsp:Policy>
                    <sp:KerberosToken
                        sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                        <wsp:Policy>
                            <sp:WssGssKerberosV5ApReqToken11/>
                        </wsp:Policy>
                    </sp:KerberosToken>
                </wsp:Policy>
            </sp:SignedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricSupportingPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SupportingTokens>
                <wsp:Policy>
                    <sp:KerberosToken
                        sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                        <wsp:Policy>
                            <sp:WssGssKerberosV5ApReqToken11/>
                        </wsp:Policy>
                    </sp:KerberosToken>
                </wsp:Policy>
            </sp:SupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosAsymmetricPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:SignedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosTransportEndorsingPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:KerberosToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                            <wsp:Policy>
                                <sp:WssGssKerberosV5ApReqToken11/>
                            </wsp:Policy>
                        </sp:KerberosToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosAsymmetricEndorsingPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:EndorsingSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:EndorsingSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricProtectionPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                         <sp:KerberosToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                            <wsp:Policy>
                              <sp:WssGssKerberosV5ApReqToken11/>
                            </wsp:Policy>
                         </sp:KerberosToken>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricDerivedProtectionPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                         <sp:KerberosToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                            <wsp:Policy>
                              <sp:WssGssKerberosV5ApReqToken11/>
                              <sp:RequireDerivedKeys />
                            </wsp:Policy>
                         </sp:KerberosToken>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItKerberosAsymmetricSignedEndorsingPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedEndorsingSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:SignedEndorsingSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
     <wsp:Policy wsu:Id="DoubleItKerberosAsymmetricSignedEncryptedPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedEncryptedSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:SignedEncryptedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricEndorsingEncryptedPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:EndorsingEncryptedSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:EndorsingEncryptedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItKerberosSymmetricSignedEndorsingEncryptedPolicy">
       <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic128/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedEndorsingEncryptedSupportingTokens>
               <wsp:Policy>
                  <sp:KerberosToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Once">
                      <wsp:Policy>
                          <sp:WssGssKerberosV5ApReqToken11/>
                      </wsp:Policy>
                  </sp:KerberosToken>
              </wsp:Policy>
            </sp:SignedEndorsingEncryptedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    
    <wsp:Policy wsu:Id="DoubleItBinding_DoubleIt_Input_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
   <wsp:Policy wsu:Id="DoubleItBinding_DoubleIt_Output_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
    
</wsdl:definitions>
