<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<wsdl:definitions name="DoubleIt"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/contract/DoubleIt"
    targetNamespace="http://www.example.org/contract/DoubleIt" 
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsaws="http://www.w3.org/2005/08/addressing" 
    xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
    xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">

    <wsdl:import location="src/test/resources/DoubleItLogical.wsdl" 
                 namespace="http://www.example.org/contract/DoubleIt"/>

    <wsdl:binding name="DoubleItSaml1TransportBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml1TransportPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml1SelfSignedTransportBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml1SelfSignedTransportPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2EndorsingTransportBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2EndorsingTransportPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2SymmetricBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2SymmetricPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2SymmetricSupportingBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2SymmetricSupportingPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
     <wsdl:binding name="DoubleItSaml2SymmetricSignedElementsBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2SymmetricSignedElementsPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2AsymmetricBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2AsymmetricPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItAsymmetricSamlInitiatorBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItAsymmetricSamlInitiatorPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2AsymmetricSignedEncryptedBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2AsymmetricSignedEncryptedPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2AsymmetricEncryptedBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2AsymmetricEncryptedPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItSaml2EndorsingEncryptedTransportBinding" type="tns:DoubleItPortType">
        <wsp:PolicyReference URI="#DoubleItSaml2EndorsingEncryptedTransportPolicy" />
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <wsp:PolicyReference URI="#DoubleItBinding_DoubleIt_Output_Policy"/>
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="DoubleItInlinePolicyBinding" type="tns:DoubleItPortType">
        <soap:binding style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DoubleIt">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="DoubleItFault">
                <soap:body use="literal" name="DoubleItFault" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="DoubleItService">
        <wsdl:port name="DoubleItSaml1TransportPort" binding="tns:DoubleItSaml1TransportBinding">
            <soap:address location="https://localhost:9009/DoubleItSaml1Transport" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2SymmetricPort" binding="tns:DoubleItSaml2SymmetricBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2Symmetric" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2SymmetricSupportingPort" 
                   binding="tns:DoubleItSaml2SymmetricSupportingBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2Symmetric" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2AsymmetricPort" binding="tns:DoubleItSaml2AsymmetricBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2Asymmetric" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml1SelfSignedTransportPort" 
                   binding="tns:DoubleItSaml1SelfSignedTransportBinding">
            <soap:address location="https://localhost:9009/DoubleItSaml1SelfSignedTransport" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2EndorsingTransportPort" 
                   binding="tns:DoubleItSaml2EndorsingTransportBinding">
            <soap:address location="https://localhost:9009/DoubleItSaml2EndorsingTransport" />
        </wsdl:port>
        <wsdl:port name="DoubleItAsymmetricSamlInitiatorPort" 
                   binding="tns:DoubleItAsymmetricSamlInitiatorBinding">
            <soap:address location="http://localhost:9001/DoubleItAsymmetricSamlInitiator" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2SymmetricSignedElementsPort" 
                   binding="tns:DoubleItSaml2SymmetricSignedElementsBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2SymmetricSignedElements" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2AsymmetricSignedEncryptedPort" 
                   binding="tns:DoubleItSaml2AsymmetricSignedEncryptedBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2AsymmetricSignedEncrypted" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2AsymmetricEncryptedPort" 
                   binding="tns:DoubleItSaml2AsymmetricEncryptedBinding">
            <soap:address location="http://localhost:9001/DoubleItSaml2AsymmetricEncrypted" />
        </wsdl:port>
        <wsdl:port name="DoubleItSaml2EndorsingEncryptedTransportPort" 
                   binding="tns:DoubleItSaml2EndorsingEncryptedTransportBinding">
            <soap:address location="https://localhost:9009/DoubleItSaml2EndorsingEncryptedTransport" />
        </wsdl:port>
        <wsdl:port name="DoubleItInlinePolicyPort" binding="tns:DoubleItInlinePolicyBinding">
            <soap:address location="https://localhost:9009/DoubleItSamlInlinePolicy" />
        </wsdl:port>
    </wsdl:service>

    <wsp:Policy wsu:Id="DoubleItSaml1TransportPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV11Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml1SelfSignedTransportPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SignedSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV11Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2EndorsingTransportPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2SymmetricPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedSupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
               </wsp:Policy>
            </sp:SignedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2SymmetricSupportingPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
               </wsp:Policy>
            </sp:SupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2SymmetricSignedElementsPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireThumbprintReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedSupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
               </wsp:Policy>
            </sp:SignedSupportingTokens>
            <sp:SignedElements>
                <sp:XPath>//saml2:Assertion</sp:XPath>
            </sp:SignedElements>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2AsymmetricPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedSupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
              </wsp:Policy>
            </sp:SignedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItAsymmetricSamlInitiatorPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
             <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:SamlToken
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssSamlV20Token11/>
                           </wsp:Policy>
                       </sp:SamlToken>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2AsymmetricSignedEncryptedPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:SignedEncryptedSupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
              </wsp:Policy>
            </sp:SignedEncryptedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2AsymmetricEncryptedPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:AsymmetricBinding>
               <wsp:Policy>
                  <sp:InitiatorToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:InitiatorToken>
                  <sp:RecipientToken>
                     <wsp:Policy>
                        <sp:X509Token
                           sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                           <wsp:Policy>
                              <sp:WssX509V3Token10 />
                              <sp:RequireIssuerSerialReference />
                           </wsp:Policy>
                        </sp:X509Token>
                     </wsp:Policy>
                  </sp:RecipientToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:AsymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:EncryptedSupportingTokens>
               <wsp:Policy>
                  <sp:SamlToken
                      sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                      <wsp:Policy>
                         <sp:WssSamlV20Token11/>
                      </wsp:Policy>
                  </sp:SamlToken>
              </wsp:Policy>
            </sp:EncryptedSupportingTokens>
         </wsp:All>
      </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="DoubleItSaml2EndorsingEncryptedTransportPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false" />
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax />
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp />
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128 />
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingEncryptedSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingEncryptedSupportingTokens>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
   
    <wsp:Policy wsu:Id="DoubleItBinding_DoubleIt_Input_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
   <wsp:Policy wsu:Id="DoubleItBinding_DoubleIt_Output_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
               <sp:Header Namespace="http://WSSec/saml"/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
    
</wsdl:definitions>
